OFICIOS = {
    "Albañil": ["albañil", "albañila", "peón albañil", "peon albañil", "mampostero", "mampostería"],
    "Oficial Albañil": ["oficial albañil"],
    "Ayudante Albañil": ["ayudante albañil"],
    "Soldador": ["soldador", "soldadora", "soldadura", "suelda"],
    "Soldador TIG": ["soldador tig", "tig"],
    "Soldador MIG/MAG": ["soldador mig", "soldador mag", "mig", "mag"],
    "Soldador Autógeno": ["autógeno", "oxigenista"],
    "Soldador de Cañerías": ["soldador cañerías", "soldador de cañeria"],
    "Soldador Eléctrico": ["soldador eléctrico", "soldador electrico"],
    "Electricista": ["electricista", "electricidad", "instalación eléctrica"],
    "Electricista de Obra": ["electricista de obra"],
    "Electricista de Baja Tensión": ["baja tensión", "baja tension"],
    "Electricista de Media Tensión": ["media tensión", "media tension"],
    "Electricista de Alta Tensión": ["alta tensión", "alta tension"],
    "Electricista Conexionista": ["conexionista"],
    "Electricista Montador": ["electricista montador"],
    "Plomero": ["plomero", "plomera", "plomería", "plomeria", "fontanero", "sanitario"],
    "Gasista": ["gasista", "gasista natural", "gas matriculado"],
    "Refrigeración": ["refrigeración", "refrigeracion", "aire acondicionado", "climatización"],
    "Carpintero": ["carpintero", "carpintera", "carpintería", "carpinteria", "ebanista"],
    "Carpintero de Obra": ["carpintero obra"],
    "Carpintero de Encofrados": ["carpintero encofrados", "encofrador"],
    "Carpintero Metálico": ["carpintero metálico", "estructuras metálicas"],
    "Herrero": ["herrero", "herrera", "herrería", "herreria", "forjador"],
    "Mecánico": ["mecanico", "mecánica", "mecanica"],
    "Mecánico Automotriz": ["mecánico automotriz", "mecanico automotriz", "automotor"],
    "Mecánico de Equipos Pesados": ["mecánico equipos pesados", "equipos pesados", "maquinaria pesada"],
    "Mecánico de Montaje": ["mecánico montaje"],
    "Mecánico de Plantas": ["mecánico plantas", "planta hormigonera"],
    "Pintor": ["pintor", "pintora", "pintura"],
    "Pintor de Obra": ["pintor obra"],
    "Chofer": ["chofer", "conductor", "chófer"],
    "Chofer de Camioneta": ["chofer camioneta", "conductor camioneta"],
    "Chofer de Automóvil": ["chofer automovil", "conductor automovil"],
    "Chofer de Camión": ["camión rígido", "camión articulado", "camion rigido", "camion articulado"],
    "Chofer de Volqueta": ["volqueta"],
    "Chofer de Microtransporte": ["microtransporte", "transporte personal"],
    "Chofer de Transporte de Áridos": ["transporte áridos", "transporte agregados"],
    "Chofer de Transporte de Hormigón": ["transporte hormigón", "transporte concreto"],
    "Chofer de Transporte de Combustible": ["transporte combustible"],
    "Chofer de Transporte de Equip Pesado": ["transporte equipos pesados"],
    "Amolador": ["amolador", "amoladora"],
    "Amolador de Herramientas": ["amolador herramientas"],
    "Encofrador": ["encofrador", "encofradora", "encofrados"],
    "Ferrero": ["ferrero", "ferrea", "fierrero", "armado de hierro", "armador de hierro"],
    "Yesero": ["yesero", "yesera"],
    "Mason": ["mason"],
    "Operador de Maquinaria": ["operador", "operador de maquinaria", "maquinista"],
    "Operador de Excavadora": ["excavadora"],
    "Operador de Retroexcavadora": ["retroexcavadora", "retropala"],
    "Operador de Topadora": ["topadora"],
    "Operador de Motoniveladora": ["motoniveladora"],
    "Operador de Cargadora Frontal": ["cargadora frontal", "cargadora"],
    "Operador de Compactador": ["compactador", "compactadora"],
    "Operador de Rodillo": ["rodillo estático", "rodillo neumático", "rodillo vibratorio", "rodillo"],
    "Operador de Autoelevador": ["autoelevador"],
    "Operador de Montacargas": ["montacargas"],
    "Operador de Grúa": ["operador de grúa", "grúa", "gruista"],
    "Operador de Grúa de Pluma": ["grúa de pluma", "operador grua pluma"],
    "Operador de Hidrogrúa": ["hidrogrúa", "hidrogra", "operador hidrogrua"],
    "Operador de Plataforma": ["plataforma soportada", "plataforma pluma"],
    "Operador de Compresora": ["compresora", "compresor"],
    "Operador de Planta de Hormigón": ["planta hormigonera", "planta concreto"],
    "Operador de Vibradora": ["vibradora hormigon", "vibradora concreto"],
    "Operador de Demoledora": ["demoledora"],
    "Operador de Tractor": ["tractor"],
    "Operador de Radio": ["radio obra"],
    "Operador de Ultrasonido": ["ultrasonido"],
    "Operador de Prueba Hidráulica": ["prueba hidráulica"],
    "Operador de Tratamiento Térmico": ["tratamiento térmico"],
    "Tornero": ["tornero", "tornero fresador"],
    "Chapista": ["chapista", "chapa"],
    "Vidriero": ["vidriero", "vidrio"],
    "Colocador": ["colocador", "colocadora", "colocación pisos", "colocacion"],
    "Techador": ["techador", "techista", "techo"],
    "Impermeabilizador": ["impermeabilizador", "impermeabilización"],
    "Jardinero": ["jardinero", "jardinería", "paisajista"],
    "Seguridad": ["prevencionista", "prevención riesgos", "seguridad higiene", "higiene seguridad", "seguridad e higiene"],
    "Montador": ["montador", "montaje industrial"],
    "Montador de Estructuras": ["montador estructuras"],
    "Montador de Tanques": ["montador tanques"],
    "Montador en General": ["montador general"],
    "Tubero": ["tubero", "tuberías", "tuberia"],
    "Cañista": ["cañista", "cañerías"],
    "Instrumentista": ["instrumentista", "instrumentación"],
    "Dinamitero": ["dinamitero", "perforista", "cargador tiro"],
    "Machetero": ["machetero", "desmonte"],
    "Machetero Alpinista": ["machetero alpinista", "alpinista"],
    "Biselador": ["biselador"],
    "Curvador": ["curvador"],
    "Argonista": ["argonista"],
    "Banderillero": ["banderillero"],
    "Calchero": ["calchero"],
    "Carretonero": ["carretonero"],
    "Cepillero": ["cepillero"],
    "Cocinero": ["cocinero", "encargado cocina"],
    "Oxigenista": ["oxigenista"],
    "Pañolero": ["pañolero"],
    "Radiólogo": ["radiologo", "radiología"],
    "Revestidor": ["revestidor"],
    "Sereno": ["sereno"],
    "Soportista": ["soportista"],
    "Topógrafo": ["topografo", "topografía", "agrimensor"],
    "Engrasador": ["engrasador"],
     "Cepillador": ["cepillador"],
     "Maestranza": ["maestranza", "cuadrilla", "brigada", "tareas generales", "mantenimiento general"],
     "Peón": ["peón", "peon", "peón de obra", "peon de obra", "jornalero", "jornal"],
     "Peón Calificado": ["peón calificado", "peon calificado", "oficial peón"],
     "Medio Oficial": ["medio oficial", "semioficial"],
     "Oficial": ["oficial", "oficial de obra"],
     "Capataz": ["capataz", "capataz de obra", "jefe de cuadrilla"],
     "Jefe de Obra": ["jefe de obra", "maestro mayor", "residente de obra"],
     "Ayudante Albañil": ["ayudante albañil", "ayudante de albañil", "peón albañil", "peon albañil"],
     "Ayudante Electricista": ["ayudante electricista", "ayudante de electricista"],
     "Ayudante Plomero": ["ayudante plomero", "ayudante de plomero"],
     "Ayudante Carpintero": ["ayudante carpintero", "ayudante de carpintero"],
     "Tareas Generales": ["tarea general", "tareas generales", "peón general", "peon general", "labores generales"],
     "Yesero": ["yesero", "yesera"],
}

CATEGORIAS = {
    "Albañilería y Estructuras": [
        "Albañil", "Oficial Albañil", "Ayudante Albañil",
        "Peón", "Peón Calificado", "Medio Oficial", "Oficial", "Capataz", "Jefe de Obra",
        "Encofrador", "Ferrero", "Machetero", "Machetero Alpinista",
        "Amolador", "Amolador de Herramientas",
        "Banderillero", "Calchero", "Carretonero", "Cepillero", "Cepillador",
        "Mason",
    ],
    "Electricidad": [
        "Electricista", "Electricista de Obra",
        "Electricista de Baja Tensión", "Electricista de Media Tensión",
        "Electricista de Alta Tensión", "Electricista Conexionista",
        "Electricista Montador", "Ayudante Electricista",
    ],
    "Soldadura": [
        "Soldador", "Soldador TIG", "Soldador MIG/MAG",
        "Soldador Autógeno", "Soldador de Cañerías", "Soldador Eléctrico",
        "Argonista", "Biselador", "Curvador", "Oxigenista",
    ],
    "Carpintería": [
        "Carpintero", "Carpintero de Obra",
        "Carpintero de Encofrados", "Carpintero Metálico",
        "Ayudante Carpintero",
    ],
    "Plomería, Gas y Clima": [
        "Plomero", "Ayudante Plomero",
        "Gasista", "Refrigeración",
        "Tubero", "Cañista",
    ],
    "Pintura y Revestimientos": [
        "Pintor", "Pintor de Obra",
        "Yesero", "Revestidor", "Colocador",
        "Techador", "Impermeabilizador",
    ],
    "Maquinaria Pesada": [
        "Operador de Maquinaria", "Operador de Excavadora",
        "Operador de Retroexcavadora", "Operador de Topadora",
        "Operador de Motoniveladora", "Operador de Cargadora Frontal",
        "Operador de Compactador", "Operador de Rodillo",
        "Operador de Autoelevador", "Operador de Montacargas",
        "Operador de Grúa", "Operador de Grúa de Pluma",
        "Operador de Hidrogrúa", "Operador de Plataforma",
        "Operador de Compresora", "Operador de Planta de Hormigón",
        "Operador de Vibradora", "Operador de Demoledora",
        "Operador de Tractor",
    ],
    "Conductores": [
        "Chofer", "Chofer de Camioneta", "Chofer de Automóvil",
        "Chofer de Camión", "Chofer de Volqueta",
        "Chofer de Microtransporte",
        "Chofer de Transporte de Áridos", "Chofer de Transporte de Hormigón",
        "Chofer de Transporte de Combustible", "Chofer de Transporte de Equip Pesado",
    ],
    "Montaje y Herreros": [
        "Montador", "Montador de Estructuras", "Montador de Tanques",
        "Montador en General", "Herrero", "Chapista", "Soportista",
    ],
    "Mecánica": [
        "Mecánico", "Mecánico Automotriz",
        "Mecánico de Equipos Pesados", "Mecánico de Montaje",
        "Mecánico de Plantas", "Tornero", "Engrasador",
    ],
    "Equipos Especiales": [
        "Operador de Radio", "Operador de Ultrasonido",
        "Operador de Prueba Hidráulica", "Operador de Tratamiento Térmico",
        "Instrumentista", "Dinamitero", "Topógrafo", "Radiólogo",
    ],
    "Varios": [
        "Jardinero", "Cocinero", "Sereno", "Pañolero",
        "Vidriero", "Maestranza", "Tareas Generales",
        "Seguridad",
    ],
}


def get_all_oficios():
    return list(OFICIOS.keys())


def get_categorias():
    return {cat: sorted(ofs) for cat, ofs in CATEGORIAS.items()}


def get_keywords_oficio(oficio):
    return OFICIOS.get(oficio, [])
